module.exports = {
  extends: ['plugin:import/errors', 'plugin:import/warnings', 'prettier'],
  plugins: ['simple-import-sort', 'prettier', 'import'],
  rules: {
    'max-len': ['error', { code: 120 }],
    'prettier/prettier': ['error'],
    quotes: ['error', 'single', { avoidEscape: true }],
    'sort-imports': 'off',
    'simple-import-sort/imports': 'error',
    'simple-import-sort/exports': 'error',
    'block-scoped-var': 'error',
    'class-methods-use-this': 'off',
    curly: 'error',
    'default-case': 'error',
    'default-case-last': 'error',
    'default-param-last': ['error'],
    'dot-notation': 'error',
    eqeqeq: ['error', 'always'],
    'no-else-return': 'error',
    'no-empty-function': ['error', { allow: ['constructors'] }],
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-floating-decimal': 'error',
    'no-magic-numbers': 'off',
    'no-new': 'error',
    'no-new-wrappers': 'error',
    'no-param-reassign': ['error', { props: true }],
    'no-redeclare': 'error',
    'no-useless-return': 'error',
    'prefer-regex-literals': 'error',
    radix: 'error',
    'require-await': 'error',
    'require-unicode-regexp': 'off',
    yoda: 'error',
    'init-declarations': ['error', 'always'],
    'no-use-before-define': 'off',
    'array-bracket-spacing': ['error', 'never'],
    'import/no-default-export': 'warn',
  },
};
